name: Markdown

on:
  pull_request:
    branches: [main]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar código
        uses: actions/checkout@v2

      - name: Instalar markdownlint
        run: npm install -g markdownlint-cli

      - name: Ejecutar markdownlint
        run: markdownlint "**/*.md"
